GET http://localhost:8080/api/foodlogs?yearMonth=2026-07&page=0&size=20
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg1MzMwLCJleHAiOjE3ODUwODg5MzB9.xVLQsXQzL7tr1UcT8tOVif0RSQL5ex8W208PS7e5DBUnvjLP4PgIoMV4L_R8d8Lv3b87zOHy4mzBRd-i8EHoCg

###

GET http://localhost:8080/api/foodlogs/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg1MzMwLCJleHAiOjE3ODUwODg5MzB9.xVLQsXQzL7tr1UcT8tOVif0RSQL5ex8W208PS7e5DBUnvjLP4PgIoMV4L_R8d8Lv3b87zOHy4mzBRd-i8EHoCg


###
GET http://localhost:8080/api/statistics/monthly?yearMonth=2026-07
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MjAzMzEwLCJleHAiOjE3ODUyMDY5MTB9.LsHxoHL4FZIEVk1SWOLZyqHlxJSF3zpFG6fIQnfRp-Nbk-bGOTHD8hjd42aEpfpeXkUKfDIAQ7M11ELcqF9Qew


###
GET http://localhost:8080/api/foodlogs/search?keyword=제육&from=2026-07-01&to=2026-07-31&page=0&size=20
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MjAzMzEwLCJleHAiOjE3ODUyMDY5MTB9.LsHxoHL4FZIEVk1SWOLZyqHlxJSF3zpFG6fIQnfRp-Nbk-bGOTHD8hjd42aEpfpeXkUKfDIAQ7M11ELcqF9Qew


###
GET http://localhost:8080/api/foodlogs/search?from=2026-07-01&to=2026-07-31&minCalorie=100&maxCalorie=1000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MjAzMzEwLCJleHAiOjE3ODUyMDY5MTB9.LsHxoHL4FZIEVk1SWOLZyqHlxJSF3zpFG6fIQnfRp-Nbk-bGOTHD8hjd42aEpfpeXkUKfDIAQ7M11ELcqF9Qew


###
GET http://localhost:8080/api/foodlogs/export?yearMonth=2026-07
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MjAzMzEwLCJleHAiOjE3ODUyMDY5MTB9.LsHxoHL4FZIEVk1SWOLZyqHlxJSF3zpFG6fIQnfRp-Nbk-bGOTHD8hjd42aEpfpeXkUKfDIAQ7M11ELcqF9Qew


###
GET http://localhost:8080/api/goals?yearMonth=2026-07
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MjEyNzIxLCJleHAiOjE3ODUyMTYzMjF9.zDGOi459Yoz_oyPIDV4sEGuX38kr9fKzASp-PTHuX3TBBD7kwqO5_eai8lalKgu3yGSsiMZANqM1bIhz5RoMtw
