POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "hong@dietlog.com",
  "password": "pass1234!",
  "nickname": "홍길동"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "hong@dietlog.com",
"password": "pass1234!"
}


###
POST http://localhost:8080/api/categories
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg2NTI3LCJleHAiOjE3ODUwOTAxMjd9.FiusA3R_-QNWF1z085osUuz94c68wQTklipUP8mrmX_E8rLfLwVgLCCQY-9l22WgidcMuX5pbFwWMidmN0KswA
Content-Type: application/json

{
  "name": "점심 한식",
  "mealType": "LUNCH",
  "foodGroup": "한식"
}

###
POST http://localhost:8080/api/foodlogs
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg2NTI3LCJleHAiOjE3ODUwOTAxMjd9.FiusA3R_-QNWF1z085osUuz94c68wQTklipUP8mrmX_E8rLfLwVgLCCQY-9l22WgidcMuX5pbFwWMidmN0KswA
Content-Type: application/json

{
  "mealType": "LUNCH",
  "calorie": 650,
  "categoryId": 1,
  "memo": "제육볶음 정식",
  "logDate": "2026-07-08"
}

###
POST http://localhost:8080/api/auth/reissue
Content-Type: application/json

{
  "refreshToken": "eb4ec81b-5da2-4201-a092-6eb7b1d33a01"
}