POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "hong@dietlog.com",
  "password": "pass1234!",
  "nickname": "홍길동"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "hong@dietlog.com",
"password": "pass1234!"
}


###
POST http://localhost:8080/api/categories
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg1MzMwLCJleHAiOjE3ODUwODg5MzB9.xVLQsXQzL7tr1UcT8tOVif0RSQL5ex8W208PS7e5DBUnvjLP4PgIoMV4L_R8d8Lv3b87zOHy4mzBRd-i8EHoCg
Content-Type: application/json

{
  "name": "점심 한식",
  "mealType": "LUNCH",
  "foodGroup": "한식"
}

###
POST http://localhost:8080/api/foodlogs
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MDg1MzMwLCJleHAiOjE3ODUwODg5MzB9.xVLQsXQzL7tr1UcT8tOVif0RSQL5ex8W208PS7e5DBUnvjLP4PgIoMV4L_R8d8Lv3b87zOHy4mzBRd-i8EHoCg
Content-Type: application/json

{
  "mealType": "LUNCH",
  "calorie": 650,
  "categoryId": 1,
  "memo": "제육볶음 정식",
  "logDate": "2026-07-08"
}

